### ISSUE TITLE
Improved repository status tracking

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-updater#973]
Currently repository status updates (new → active ↔ legacy) is not really tied to actual repository updates and thus not always correct. Improvement is needed, which may use the following logic: instead of `deprecate_repositories`+`add_repositories` in `database_update_pre`, compare list of repositories in the database with list of repositories from config. Added repositories are inserted with `new` status (and here we have chance to carefully choose unused ID and avoid problem with autoincremented smallint ID overflow), removed repositories are switched to `legacy` status. Then after updating packages, actual repositories are marked as `active`. This is also compatible with future per-repository updates.

While here, can also
- [x] add json `metadata` field for #735 (without removing existing columns yet for comatibility)
- [x] add `last_updated` field for #972
- [x] move ruleset hash into `repositories` table, as it currently resides in the separate table for no apparent reason
